02-26 18:33:27 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE PERSON
 
ID[*] INT,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
AGE INT
  "
Syntax error in SQL statement "CREATE TABLE PERSON
 
ID[*] INT,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
AGE INT
  "; SQL statement:
create table person
 
id int,
fname varchar(50),
lname varchar(50),
age int
  [42000-170]
02-26 18:36:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "CREATE TABLE PERSON
 
ID[*] INTEGER,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
AGE INTEGER
  "
Syntax error in SQL statement "CREATE TABLE PERSON
 
ID[*] INTEGER,
FNAME VARCHAR(50),
LNAME VARCHAR(50),
AGE INTEGER
  "; SQL statement:
create table person
 
id integer,
fname varchar(50),
lname varchar(50),
age integer
  [42000-170]
02-26 18:39:51 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:292)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:394)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:294)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:281)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:231)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:324)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1454)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2048)
02-26 18:39:51 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:292)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:394)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:294)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:281)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:192)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:325)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1454)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2048)
02-28 12:32:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Таблица "PERSON" уже существует
Table "PERSON" already exists; SQL statement:
create table person
(
id int,
fname varchar(50),
lname varchar(50),
age int
) [42101-170]
02-28 12:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:41:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:42:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.action.ExecuteCommandAction.enable(ExecuteCommandAction.java:66)
	at org.openide.util.actions.NodeAction$DelegateAction.resultChanged(NodeAction.java:615)
	at org.openide.util.actions.NodeAction$DelegateAction.<init>(NodeAction.java:560)
	at org.openide.util.actions.NodeAction.createContextAwareInstance(NodeAction.java:357)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2763)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2859)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1554)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mousePressed(MouseUtils.java:180)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6502)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:682)
	at java.awt.EventQueue$3.run(EventQueue.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:696)
	at java.awt.EventQueue$4.run(EventQueue.java:694)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:158)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
02-28 12:42:01 jdbc[4]: null
org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.netbeans.modules.db.explorer.DbDriverManager.getConnection(DbDriverManager.java:131)
	at org.netbeans.modules.db.explorer.DatabaseConnection.doConnect(DatabaseConnection.java:806)
	at org.netbeans.modules.db.explorer.DatabaseConnection.access$100(DatabaseConnection.java:98)
	at org.netbeans.modules.db.explorer.DatabaseConnection$2.run(DatabaseConnection.java:872)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
Caused by: org.h2.jdbc.JdbcSQLException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 13 more
02-28 12:42:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:42:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:42:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:42:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-170]
02-28 12:52:43 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-170]
02-28 12:58:21 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-170]
02-28 12:58:40 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.action.ExecuteCommandAction.enable(ExecuteCommandAction.java:66)
	at org.openide.util.actions.NodeAction$DelegateAction.resultChanged(NodeAction.java:615)
	at org.openide.util.actions.NodeAction$DelegateAction.<init>(NodeAction.java:560)
	at org.openide.util.actions.NodeAction.createContextAwareInstance(NodeAction.java:357)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2763)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2859)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1554)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mousePressed(MouseUtils.java:180)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6502)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:682)
	at java.awt.EventQueue$3.run(EventQueue.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:696)
	at java.awt.EventQueue$4.run(EventQueue.java:694)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:158)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
02-28 12:58:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:58:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 12:58:41 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:00:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:00:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:00:27 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:02:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.removeAllNodes(NodeProvider.java:224)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.removeAllNodes(NodeRegistry.java:154)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:321)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:02:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode.refresh(BaseNode.java:188)
	at org.netbeans.modules.db.explorer.node.ConnectionNode$2.run(ConnectionNode.java:322)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:02:49 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.node.ConnectionNode.getIconBase(ConnectionNode.java:391)
	at org.netbeans.api.db.explorer.node.BaseNode.updateProperties(BaseNode.java:290)
	at org.netbeans.api.db.explorer.node.BaseNode.update(BaseNode.java:277)
	at org.netbeans.api.db.explorer.node.BaseNode$1.stateChanged(BaseNode.java:227)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.stateChanged(NodeRegistry.java:182)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:133)
	at org.openide.util.ChangeSupport.fireChange(ChangeSupport.java:119)
	at org.netbeans.api.db.explorer.node.NodeProvider.setNodes(NodeProvider.java:191)
	at org.netbeans.modules.db.explorer.node.CatalogNodeProvider.initialize(CatalogNodeProvider.java:141)
	at org.netbeans.api.db.explorer.node.NodeProvider.getNodes(NodeProvider.java:107)
	at org.netbeans.modules.db.explorer.node.NodeRegistry.getNodes(NodeRegistry.java:167)
	at org.netbeans.api.db.explorer.node.ChildNodeFactory.createKeys(ChildNodeFactory.java:107)
	at org.openide.nodes.AsynchChildren.run(AsynchChildren.java:206)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1452)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2032)
02-28 13:03:05 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Объект уже закрыт
The object is already closed [90007-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1388)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1366)
	at org.h2.jdbc.JdbcConnection.getWarnings(JdbcConnection.java:588)
	at org.netbeans.modules.db.explorer.DatabaseConnection.isVitalConnection(DatabaseConnection.java:287)
	at org.netbeans.modules.db.explorer.action.ExecuteCommandAction.enable(ExecuteCommandAction.java:66)
	at org.openide.util.actions.NodeAction$DelegateAction.resultChanged(NodeAction.java:615)
	at org.openide.util.actions.NodeAction$DelegateAction.<init>(NodeAction.java:560)
	at org.openide.util.actions.NodeAction.createContextAwareInstance(NodeAction.java:357)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2763)
	at org.openide.util.Utilities.actionsToPopup(Utilities.java:2859)
	at org.openide.explorer.view.TreeView.createPopup(TreeView.java:1058)
	at org.openide.explorer.view.TreeView$PopupAdapter.showPopup(TreeView.java:1554)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.maybePopup(MouseUtils.java:189)
	at org.openide.awt.MouseUtils$PopupMouseAdapter.mousePressed(MouseUtils.java:180)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6502)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4489)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:682)
	at java.awt.EventQueue$3.run(EventQueue.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:696)
	at java.awt.EventQueue$4.run(EventQueue.java:694)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:158)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
02-28 13:03:56 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-170]
02-28 13:07:47 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Нет данных
No data is available [2000-170]
